/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_DoorSensorAbstractionSWC_.c
 * Generated on: Wed May 17 13:3:22 EDT
 ********************************************************************/

#include "string.h"
#include "Rte_DoorSensorAbstractionSWC.h"


extern Rte_DE_myuint8 ReadDoorSensor_PP_SRI_DoorState;


const Rte_CDS_DoorSensorAbstractionSWC Rte_Instance_DoorSensorAbstractionSWC = {
&ReadDoorSensor_PP_SRI_DoorState
};

const Rte_CDS_DoorSensorAbstractionSWC * const Rte_Inst_DoorSensorAbstractionSWC = &Rte_Instance_DoorSensorAbstractionSWC;




void Rte_IWrite_DoorSensorAbstractionSWC_ReadDoorSensor_PP_SRI_DoorState (myuint8 DoorState)
{
	(Rte_Inst_DoorSensorAbstractionSWC)->ReadDoorSensor_PP_SRI_DoorState->value = DoorState;
}
myuint8* Rte_IWriteRef_DoorSensorAbstractionSWC_ReadDoorSensor_PP_SRI_DoorState(void)
{
	return &(Rte_Inst_DoorSensorAbstractionSWC)->ReadDoorSensor_PP_SRI_DoorState->value;
}
